FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copiar os arquivos do projeto
COPY ["Ecommerce.csproj", "./"]
RUN dotnet restore

# Copiar todo o código fonte
COPY . .

# Publicar a aplicação
RUN dotnet publish -c Release -o /app/publish /p:UseAppHost=false

# Build da imagem final
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/publish .

# Configurar a porta
ENV ASPNETCORE_URLS=http://+:5234
EXPOSE 5234

# Configurações específicas do .NET 8
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
ENV ASPNETCORE_ENVIRONMENT=Development

# Iniciar a aplicação
ENTRYPOINT ["dotnet", "Ecommerce.dll"]